//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=android17x.database.windows.net;Initial Catalog=QL_CuaHangPhanMem;Per" +
            "sist Security Info=True;User ID=android17x;Password=Trungthachdau2023;TrustServe" +
            "rCertificate=True")]
        public string QL_CuaHangPhanMemConnectionString2 {
            get {
                return ((string)(this["QL_CuaHangPhanMemConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=android17x.database.windows.net;Initial Catalog=QL_CuaHangPhanMem;Per" +
            "sist Security Info=True;User ID=android17x;Password=Trungthachdau2023;Encrypt=Tr" +
            "ue;TrustServerCertificate=True")]
        public string QL_CuaHangPhanMemConnectionString {
            get {
                return ((string)(this["QL_CuaHangPhanMemConnectionString"]));
            }
        }
    }
}
